# Generated by Django 3.1 on 2022-07-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_slot'),
        ('carts', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slots',
            field=models.ManyToManyField(blank=True, to='team.Slot'),
        ),
    ]
