# Generated by Django 3.1 on 2022-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
