# Generated by Django 3.1 on 2022-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
